### ISSUE TITLE
Version info is confusing

### ISSUE THREAD

**Issue by MartinOtter** [JuliaDiff/DiffRules.jl#63]
The last released version of DiffRules.jl has version number 1.0.2 (according to github):

![grafik](https://user-images.githubusercontent.com/7248038/127988814-3f605554-3cd9-4e23-b1d1-407a141a18e2.png)

The master branch of DiffRules.jl has version number 1.2.1 in the Project.toml file.

Are there more registered versions of DiffRules, as shown in this github repository?

**Comment by devmotion** [comment]
I assume that there was a problem with TagBot integration but it seems to be fixed now since the latest Github release is 1.3.0. In the Pkg registry, the following versions of DiffRules are registered and can be installed: https://github.com/JuliaRegistries/General/blob/master/D/DiffRules/Versions.toml

**Comment by mcabbott** [comment]
Seems to be fixed now, https://github.com/JuliaDiff/DiffRules.jl/releases/tag/v1.3.1 shows up as the latest here, not just on the registry.
